
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ClassConfig : Luban.BeanBase
{
    public ClassConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["question"].IsString) { throw new SerializationException(); }  Question = _buf["question"]; }
        { if(!_buf["ans"].IsString) { throw new SerializationException(); }  Ans = _buf["ans"]; }
        { if(!_buf["options"].IsString) { throw new SerializationException(); }  Options = _buf["options"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
    }

    public static ClassConfig DeserializeClassConfig(JSONNode _buf)
    {
        return new ClassConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 题目
    /// </summary>
    public readonly string Question;
    /// <summary>
    /// 正确答案
    /// </summary>
    public readonly string Ans;
    /// <summary>
    /// 选项
    /// </summary>
    public readonly string Options;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
   
    public const int __ID__ = 452773562;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "question:" + Question + ","
        + "ans:" + Ans + ","
        + "options:" + Options + ","
        + "type:" + Type + ","
        + "}";
    }
}

}
