
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.classConfig
{
public partial class TbClass
{
    private readonly System.Collections.Generic.Dictionary<int, ClassConfig> _dataMap;
    private readonly System.Collections.Generic.List<ClassConfig> _dataList;
    
    public TbClass(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ClassConfig>();
        _dataList = new System.Collections.Generic.List<ClassConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ClassConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ClassConfig.DeserializeClassConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ClassConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ClassConfig> DataList => _dataList;

    public ClassConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ClassConfig Get(int key) => _dataMap[key];
    public ClassConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

