
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DoubleQuestion : Luban.BeanBase
{
    public DoubleQuestion(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["question"].IsString) { throw new SerializationException(); }  Question = _buf["question"]; }
        { if(!_buf["ans"].IsString) { throw new SerializationException(); }  Ans = _buf["ans"]; }
        { if(!_buf["ans1"].IsString) { throw new SerializationException(); }  Ans1 = _buf["ans1"]; }
        { if(!_buf["ans2"].IsString) { throw new SerializationException(); }  Ans2 = _buf["ans2"]; }
        { if(!_buf["ans3"].IsString) { throw new SerializationException(); }  Ans3 = _buf["ans3"]; }
        { if(!_buf["ans4"].IsString) { throw new SerializationException(); }  Ans4 = _buf["ans4"]; }
    }

    public static DoubleQuestion DeserializeDoubleQuestion(JSONNode _buf)
    {
        return new DoubleQuestion(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 题目
    /// </summary>
    public readonly string Question;
    /// <summary>
    /// 正确答案
    /// </summary>
    public readonly string Ans;
    /// <summary>
    /// 选项1
    /// </summary>
    public readonly string Ans1;
    /// <summary>
    /// 选项2
    /// </summary>
    public readonly string Ans2;
    /// <summary>
    /// 选项3
    /// </summary>
    public readonly string Ans3;
    /// <summary>
    /// 选项4
    /// </summary>
    public readonly string Ans4;
   
    public const int __ID__ = 969836279;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "question:" + Question + ","
        + "ans:" + Ans + ","
        + "ans1:" + Ans1 + ","
        + "ans2:" + Ans2 + ","
        + "ans3:" + Ans3 + ","
        + "ans4:" + Ans4 + ","
        + "}";
    }
}

}
