
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.single
{
public partial class TbSingle
{
    private readonly System.Collections.Generic.Dictionary<int, Single> _dataMap;
    private readonly System.Collections.Generic.List<Single> _dataList;
    
    public TbSingle(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Single>();
        _dataList = new System.Collections.Generic.List<Single>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Single _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Single.DeserializeSingle(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Single> DataMap => _dataMap;
    public System.Collections.Generic.List<Single> DataList => _dataList;

    public Single GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Single Get(int key) => _dataMap[key];
    public Single this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

