
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.studioConfig
{
public partial class TbStudio
{
    private readonly System.Collections.Generic.Dictionary<int, StudioConfig> _dataMap;
    private readonly System.Collections.Generic.List<StudioConfig> _dataList;
    
    public TbStudio(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StudioConfig>();
        _dataList = new System.Collections.Generic.List<StudioConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            StudioConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = StudioConfig.DeserializeStudioConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, StudioConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<StudioConfig> DataList => _dataList;

    public StudioConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StudioConfig Get(int key) => _dataMap[key];
    public StudioConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

