
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class StudioConfig : Luban.BeanBase
{
    public StudioConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["info"].IsString) { throw new SerializationException(); }  Info = _buf["info"]; }
        { if(!_buf["path"].IsString) { throw new SerializationException(); }  Path = _buf["path"]; }
    }

    public static StudioConfig DeserializeStudioConfig(JSONNode _buf)
    {
        return new StudioConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 题目
    /// </summary>
    public readonly string Info;
    /// <summary>
    /// 正确答案
    /// </summary>
    public readonly string Path;
   
    public const int __ID__ = -1973865256;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "info:" + Info + ","
        + "path:" + Path + ","
        + "}";
    }
}

}
