
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Cysharp.Threading.Tasks;
using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public item.TbItem TbItem {get; private set; }

    private Tables()
    {
    }

    public static async UniTask<Tables> CreateAsync(Func<string, UniTask<JSONNode>> loader)
    {
        Tables tables = new Tables();
        tables.TbItem = new item.TbItem(await loader("item_tbitem"));            
        tables.ResolveRef();
        return tables;
    }

    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
    }
}

}
